Repository dvajs/dva, pull requests merged in 2019-03, with the labels that each got.

#2015 chore: bundle with umi-library
  .gitignore
  .travis.yml
  README.md
  README_zh-CN.md
  lerna.json
  package.json
  packages/dva-core/.umirc.library.js
  packages/dva-core/index.js
  packages/dva-core/package.json
  packages/dva-core/saga.js
  packages/dva-core/src/getSaga.js
  packages/dva-core/src/index.js
  packages/dva-core/src/utils.js
  packages/dva-core/test/checkModel.test.js
  packages/dva-core/yarn.lock
  packages/dva-immer/.umirc.library.js
  packages/dva-immer/package.json
  packages/dva-immer/yarn.lock
  packages/dva-loading/.travis.yml
  packages/dva-loading/.umirc.library.js
  packages/dva-loading/README.md
  packages/dva-loading/package.json
  packages/dva-loading/src/index.js
  packages/dva-loading/yarn.lock
  packages/dva-no-router/README.md
  packages/dva-no-router/fetch.d.ts
  packages/dva-no-router/fetch.js
  packages/dva-no-router/index.d.ts
  packages/dva-no-router/index.js
  packages/dva-no-router/package.json
  packages/dva-no-router/saga.js
  packages/dva-no-router/src/index.js
  packages/dva-react-router-3/LICENSE
  packages/dva-react-router-3/README.md
  packages/dva-react-router-3/fetch.js
  packages/dva-react-router-3/index.js
  packages/dva-react-router-3/package.json
  packages/dva-react-router-3/router.js
  packages/dva-react-router-3/saga.js
  packages/dva-react-router-3/src/index.js
  packages/dva-react-router-3/test/index-test.js
  packages/dva/.umirc.library.js
  packages/dva/dynamic.js
  packages/dva/index.js
  packages/dva/package.json
  packages/dva/src/dynamic.js
  packages/dva/src/index.js
  packages/dva/umd/dva.js
  packages/dva/umd/dynamic.js
  packages/dva/umd/router.js
  packages/dva/umd/test-umd.html
  packages/dva/yarn.lock
  rollup.config.js
  scripts/build.js
  scripts/umd.js
  website/yarn.lock
  yarn.lock
Labels: enhancement

#2021 dep: upgrade redux to 4
  lerna.json
  packages/dva-core/package.json
  packages/dva/package.json
Labels: pr: dependency

#2022 dep: upgrade react-redux to 6
  package.json
  packages/dva/package.json
  packages/dva/src/index.js
  packages/dva/test/index.e2e.js
  packages/dva/yarn.lock
  yarn.lock
Labels: pr: dependency

#2023 feat: expost history methods
  packages/dva/src/index.js
  packages/dva/test/index.e2e.js
Labels: pr: enhancement

#2024 dep: upgrade immer to 2
  packages/dva-immer/package.json
Labels: pr: dependency

#2027 fix: 修复文档
  docs/guide/source-code-explore.md
Labels: documentation

#2026 fix: 修复文档中使用 **** 加粗 但实际预览中没有加粗的问题
  docs/guide/source-code-explore.md
Labels: pr: documentation

#2025 Update develop-complex-spa.md
  docs/guide/develop-complex-spa.md
Labels: pr: documentation

#2031 Update source-code-explore.md
  docs/guide/source-code-explore.md
Labels: pr: documentation
