Repository dvajs/dva, pull requests merged in 2019-11, with the labels that each got.

#2231 dep: upgrade connected-react-router to 6.5.2
  .circleci/config.yml
  .github/workflows/ci.yml
  packages/dva/package.json
  packages/dva/test/index.e2e.js
Labels: pr(dependency)

#2233 Update README_zh-CN.md
  README_zh-CN.md
Labels: pr(documentation)

#2234 fix: route push problem with subscription in prod mode
  packages/dva-core/test/effects.test.js
  packages/dva/src/index.js
Labels: pr(bug)

#2219 feat: add dispatch type definition
  packages/dva/index.d.ts
Labels: pr(bug)

#2241 :arrow_up: upgrad react-router-dom and @types/react-router-dom
  package.json
  packages/dva/index.d.ts
  packages/dva/package.json
  packages/dva/src/index.js
  packages/dva/test/index.test.js
  packages/dva/yarn.lock
  yarn.lock
Labels: pr(enhancement)

#2250 fix: Dispatch duplicated typing in index.d.ts
  packages/dva/index.d.ts
Labels: pr(bug)
